### ISSUE TITLE
CentOS build 

### ISSUE THREAD

**Issue by rs0h** [cmouse/ecies#1]
Sadly, but project can't be built under CentOS 7 despite the fact it has OpenSSL devel version >1.0, because of lack of the function `EC_POINT_get_affine_coordinates_GF2m`.

CentOS 7, build using devtoolset-6 (gcc 6.2.1), OpenSSL 1.0.1e

```
r@CentOS ecies]$ make
gcc  -o ecies ecies.o -lssl -lcrypto
ecies.o: In function `EC_KEY_public_derive_S':
/home/r/ecies/ecies.c:66: undefined reference to `EC_POINT_get_affine_coordinates_GF2m'
ecies.o: In function `EC_KEY_private_derive_S':
/home/r/ecies/ecies.c:92: undefined reference to `EC_POINT_get_affine_coordinates_GF2m'
collect2: error: ld returned 1 exit status
make: *** [ecies] Error 1
```

**Comment by cmouse** [comment]
Yes, well, since this is demonstration code, the GF2m one is practically needed. You should not use this for production use, and I am not very enthusiastic on implementing that one.
